FROM scratch

LABEL maintainer {{ env "TEMP_DOCKER_MAINTAINER" }}
LABEL type "public"
LABEL versioning "simple"

ARG TOOL

ADD ./build/ /
COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["./app"]