FROM golang:1.9

LABEL maintainer {{ env "TEMP_DOCKER_MAINTAINER" }}
LABEL type "public"
LABEL versioning "simple"

ARG GIT_HOST
ARG REPO
ARG NAME
ARG COMMAND

ADD ./ /go/src/${GIT_HOST}/${REPO}/${NAME}
WORKDIR /go/src/${GIT_HOST}/${REPO}/${NAME}/

RUN make ${COMMAND}

CMD ["/bin/bash"]